CREATE DATABASE Helpers;
USE Helpers;

CREATE TABLE empresa(
	idEmpresa INT PRIMARY KEY AUTO_INCREMENT,
    razaoSocial VARCHAR(45) NOT NULL,
    CNPJ CHAR(14) UNIQUE NOT NULL,
    email VARCHAR(70) NOT NULL,
    responsavel VARCHAR(45) NOT NULL
);
